version: '3.3'
services:
  db:
    image: mysql:8.0.19
    container_name: ${DC_MYSQL_CONTAINER_NAME}
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DC_MYSQL_ROOT_PASSWORD}
    ports:
      - ${DC_MYSQL_LOCAL_PORT}:3306
    volumes:
      - ${DC_MYSQL_PATH_VOLUME}:/var/lib/mysql
    restart: always

  web:
    image: thecodingmachine/php:7.4-v3-apache
    # https://github.com/thecodingmachine/docker-images-php
    container_name: ${DC_APACHE_CONTAINER_NAME}
    env_file:
      - .env
    environment:
      PHP_EXTENSION_XDEBUG: 1
      APACHE_EXTENSION_HEADERS: 1
    ports:
      - ${DC_APACHE_LOCAL_PORT}:80
    volumes:
      - ${DC_APACHE_PATH_VOLUME}:/var/www/html
    depends_on:
      - db
    restart: always
